### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by Onepamopa** [ayufan/pve-helpers#3]
As mentioned in the README:
"You need to configure each machine to enable the hookscript."

Is this actually necessary, or can it be enabled only on 1 VM - the VM we need to optimize for performance w/o caring much about the rest?

Setup is Threadripper 3960x, 8x8GB 3200 memory.

Additionally - "In practice, most Ryzen systems work best with halt_poll_ns set to 0."
Can this be set "on the fly" while the VMs are running? Has anyone tested a good setting for TR?

Also, I'm planning of using hugepages only for the "performance" VM. Currently it's set to "normal" 32GB allocation, I assume there'd be some difference in performance when hugepages are enabled for it?

**Comment by ayufan** [comment]
> Is this actually necessary, or can it be enabled only on 1 VM - the VM we need to optimize for performance w/o caring much about the rest?

It is enough to enable on a single one, the one that you want to be pinned.

> Can this be set "on the fly" while the VMs are running? 

Yes.

> I assume there'd be some difference in performance when hugepages are enabled for it?

I noticed that in some cases the lack of hugepages results in worse performance in a VM, especially when gaming. I got much more consistent frames with hugepages. Secondly, it ensures that proper amount of memory is allocated always, and there's no fragmentation there.

**Comment by Onepamopa** [comment]
I'll do some experiments after setting up a PBS for backups & move to PVE 7.
