### ISSUE TITLE
If you are using isolcpus in grub you need to use "cpu_chrt fifo 1" option in this script, other wise everything will run on the first core only.

### ISSUE THREAD

**Issue by cooljimy84** [ayufan/pve-helpers#7]
Might be worth updating the docs as i just came across this issue.

https://serverfault.com/questions/573025/taskset-not-working-over-a-range-of-cores-in-isolcpus

**Comment by ayufan** [comment]
Thanks. Do you mind opening PR? In general usage of `isolcpus` is not advised as it does not bring big benefits.

**Comment by cooljimy84** [comment]
https://github.com/ayufan/pve-helpers/pull/8

**Comment by Onepamopa** [comment]
so, if we use isocpus we have to set # cpu_chrt fifo 1
I'll test this in a few days when I get some free time
